openapi: "3.0.1"
info:
  title: "Swagger AWS-Backend"
  version: "1.0"
servers:
- url: "https://aflj5z8et1.execute-api.ap-south-1.amazonaws.com/{basePath}"
  variables:
    basePath:
      default: "prod"
paths:
  /drives:
    get:
      responses:
        "200":
          description: "200 response"
          content: {}
      x-amazon-apigateway-integration:
        httpMethod: "POST"
        uri: "arn:aws:apigateway:ap-south-1:lambda:path/2015-03-31/functions/arn:aws:lambda:ap-south-1:033215165260:function:MyGetAllDrivesFunction/invocations"
        responses:
          default:
            statusCode: "200"
        passthroughBehavior: "when_no_match"
        contentHandling: "CONVERT_TO_TEXT"
        type: "aws"
components: {}
